const SKILLS_DATA = {
  "Software & Dev": [
    "JavaScript","TypeScript","Python","Java","C++","C#","Go","Rust","Ruby","PHP",
    "Swift","Kotlin","Scala","R","MATLAB","Dart","Elixir","Clojure","Haskell","F#",
    "Groovy","Lua","Julia","Erlang","Perl","C","HTML","CSS","SASS/SCSS","SQL","NoSQL",
    "React","Vue.js","Angular","Next.js","Nuxt.js","Svelte","Ember.js","jQuery",
    "Bootstrap","Tailwind CSS","Material UI","Redux","MobX","Zustand","Recoil",
    "Node.js","Express.js","Fastify","NestJS","Bun",
    "Django","Flask","FastAPI","Ruby on Rails","Spring Boot","Laravel","ASP.NET","Symfony","Gin",
    "REST APIs","GraphQL","WebSockets","gRPC","SOAP",
    "Microservices","Serverless","Event-driven architecture","Domain-driven design",
    "Test-driven development (TDD)","Behavior-driven development (BDD)",
    "Design patterns","SOLID principles","Clean architecture",
    "Git","GitHub","GitLab","Bitbucket","SVN",
    "Jest","Mocha","Chai","Cypress","Selenium","Playwright","Pytest","JUnit","TestNG",
    "Webpack","Vite","Rollup","Parcel","Babel","ESLint","Prettier",
    "Postman","Swagger","OpenAPI",
    "WebAssembly","PWA","Electron","React Native","Flutter","Xamarin","Ionic",
    "OAuth","JWT","SSL/TLS","Encryption","Zero-trust architecture",
    "MySQL","PostgreSQL","SQLite","Oracle","SQL Server","MongoDB","DynamoDB",
    "Firebase","Supabase","Neo4j","InfluxDB","Cassandra","Redis","Elasticsearch",
    "RabbitMQ","Apache Kafka",
    "Linux","Unix","Windows Server","Bash","PowerShell","Shell scripting",
    "Agile","Scrum","Kanban","SAFe",
    "Code review","Technical documentation","System design","API design",
    "Database design","Object-oriented programming (OOP)","Functional programming",
    "Concurrent programming","Performance optimization",
    "Accessibility (WCAG)","Internationalization (i18n)","Localization (l10n)",
    "Mobile development","Cross-platform development","Embedded systems",
    "IoT development","Blockchain development","Web3","Smart contracts","Solidity",
    "Unity","Unreal Engine","Game development","AR/VR development","WebGL",
    "OpenGL","Vulkan","WebAssembly"
  ],
  "Cloud & DevOps": [
    "AWS","Microsoft Azure","Google Cloud Platform (GCP)","IBM Cloud","Oracle Cloud",
    "Heroku","Vercel","Netlify","DigitalOcean","Cloudflare","Linode",
    "Docker","Kubernetes","Docker Swarm","Podman","Helm",
    "Terraform","Ansible","Puppet","Chef","Vagrant","Pulumi","CloudFormation",
    "CI/CD","Jenkins","GitHub Actions","GitLab CI/CD","CircleCI","Travis CI","ArgoCD","Flux",
    "AWS EC2","AWS S3","AWS Lambda","AWS RDS","AWS EKS","AWS ECS","AWS CloudFront",
    "Azure DevOps","Azure Functions","Azure Kubernetes Service (AKS)","Azure App Service",
    "Google Kubernetes Engine (GKE)","Google Cloud Functions","Cloud Run",
    "Prometheus","Grafana","ELK Stack","Datadog","New Relic","Sentry","OpenTelemetry",
    "Infrastructure as Code (IaC)","GitOps","DevOps","SRE","Platform engineering",
    "Load balancing","Auto-scaling","High availability","Disaster recovery",
    "Networking","VPC","DNS","CDN","Nginx","Apache","HAProxy",
    "Service mesh","Istio","Linkerd",
    "Secrets management","HashiCorp Vault","AWS Secrets Manager",
    "Cost optimization","FinOps","Cloud architecture","Multi-cloud","Serverless architecture",
    "Edge computing","Site reliability engineering (SRE)","Chaos engineering",
    "Blue-green deployment","Canary deployment","Feature flags (ops)"
  ],
  "Data & Analytics": [
    "SQL","Python","R","Excel","Power BI","Tableau","Looker","Metabase",
    "Google Analytics","Google Analytics 4 (GA4)","Google Looker Studio",
    "Adobe Analytics","Mixpanel","Amplitude","Heap","FullStory","Hotjar",
    "Qlik","SAS","SPSS","Stata",
    "Data cleaning","Data wrangling","Data modeling","Data visualization",
    "Statistical analysis","Regression analysis","Time series analysis",
    "Cohort analysis","A/B testing","Hypothesis testing",
    "Bayesian statistics","Descriptive statistics","Inferential statistics",
    "ETL","ELT","Data pipeline","Apache Spark","Hadoop","Hive",
    "Apache Airflow","dbt","Fivetran","Stitch","Databricks",
    "Snowflake","BigQuery","Amazon Redshift","Azure Synapse",
    "Data warehouse","Data lake","Data lakehouse","Delta Lake",
    "Stream processing","Batch processing","Real-time analytics",
    "Business intelligence (BI)","KPI tracking","Dashboard design",
    "Jupyter Notebooks","RStudio","Google Colab",
    "Data governance","Data quality","Master data management",
    "Data cataloging","Data lineage","GDPR data compliance",
    "Pandas","NumPy","Matplotlib","Seaborn","Plotly","SciPy",
    "Feature engineering","Predictive analytics","Prescriptive analytics",
    "Customer segmentation","Churn analysis","Revenue analytics","Product analytics",
    "Excel (advanced)","Excel VBA","Power Query","DAX","MDX",
    "Data storytelling","Executive reporting","Self-service analytics",
    "Web scraping","API data extraction","Google Sheets (advanced)"
  ],
  "AI & Machine Learning": [
    "Machine learning","Deep learning","Natural language processing (NLP)",
    "Computer vision","Reinforcement learning","Supervised learning",
    "Unsupervised learning","Semi-supervised learning","Transfer learning",
    "Neural networks","Convolutional neural networks (CNN)",
    "Recurrent neural networks (RNN)","Transformers","Large language models (LLMs)",
    "Generative AI","Diffusion models","GANs","Autoencoders","BERT","GPT",
    "TensorFlow","PyTorch","Keras","Scikit-learn","XGBoost","LightGBM","CatBoost",
    "NLTK","spaCy","Hugging Face","OpenCV","LangChain","LlamaIndex",
    "Vector databases","Pinecone","Weaviate","Chroma",
    "Prompt engineering","Fine-tuning","RLHF","RAG (Retrieval-Augmented Generation)",
    "MLOps","Model deployment","Model monitoring","Model explainability",
    "Responsible AI","AI ethics","Bias detection","Fairness in ML",
    "AutoML","Hyperparameter tuning","Experiment tracking","MLflow",
    "Weights & Biases","Neptune.ai",
    "Recommendation systems","Fraud detection","Anomaly detection",
    "Sentiment analysis","Text classification","Named entity recognition (NER)",
    "Speech recognition","Image classification","Object detection",
    "Image segmentation","Pose estimation","Time series forecasting"
  ],
  "Cybersecurity": [
    "Penetration testing","Ethical hacking","Vulnerability assessment",
    "Security auditing","Red teaming","Blue teaming","Purple teaming",
    "OWASP","NIST","CIS Controls","ISO 27001","SOC 2",
    "Network security","Application security","Cloud security","Endpoint security",
    "Identity & access management (IAM)","Zero-trust security","SIEM",
    "Intrusion detection","Intrusion prevention","Firewall management",
    "Encryption","PKI","Cryptography",
    "Threat intelligence","Threat modeling","Risk assessment",
    "Incident response","Digital forensics","Malware analysis","Reverse engineering",
    "GDPR compliance","HIPAA compliance","PCI DSS","SOX compliance",
    "Security operations center (SOC)","Vulnerability management","Patch management",
    "Security awareness training","DevSecOps","Secure SDLC","DAST","SAST",
    "Burp Suite","Metasploit","Nmap","Wireshark","Kali Linux",
    "Splunk","Microsoft Sentinel","Crowdstrike","SentinelOne",
    "DLP","CASB","SASE","Zero trust network access (ZTNA)",
    "Bug bounty","CTF (Capture the Flag)","OSINT","Social engineering awareness"
  ],
  "Marketing & Growth": [
    "SEO","Technical SEO","On-page SEO","Off-page SEO","Link building",
    "Keyword research","Local SEO","International SEO",
    "SEM","Pay-per-click (PPC)","Google Ads","Facebook Ads","Instagram Ads",
    "LinkedIn Ads","Twitter/X Ads","TikTok Ads","YouTube Ads",
    "Programmatic advertising","Display advertising","Retargeting","Affiliate marketing",
    "Email marketing","Marketing automation","Drip campaigns","Newsletter strategy",
    "HubSpot","Salesforce Marketing Cloud","Marketo","Mailchimp",
    "Klaviyo","ActiveCampaign","Braze","Iterable","Customer.io",
    "Content marketing","Blog strategy","Content calendar","Editorial planning",
    "Social media marketing","Community management","Social media strategy",
    "Influencer marketing","Creator partnerships","Brand partnerships",
    "Performance marketing","Growth hacking","Growth strategy",
    "Conversion rate optimization (CRO)","Landing page optimization",
    "A/B testing","Funnel analysis","Customer acquisition","Customer retention",
    "Lifecycle marketing","Account-based marketing (ABM)","Product marketing",
    "Go-to-market strategy","Brand management","Brand strategy","Positioning","Messaging",
    "Copywriting","Content writing","Video marketing","Podcast marketing",
    "Webinar marketing","Event marketing",
    "SEMrush","Ahrefs","Moz","Screaming Frog","Google Search Console",
    "Hootsuite","Buffer","Sprout Social",
    "Attribution modeling","Multi-touch attribution",
    "Customer journey mapping","Persona development","Market research",
    "Competitive analysis","Voice of customer","NPS","CSAT",
    "PR","Media relations","Press releases","Crisis communication",
    "Demand generation","Lead generation","MQL/SQL funnel",
    "Product-led growth (PLG)","Viral marketing","Referral programs",
    "Market sizing","TAM/SAM/SOM","Revenue marketing","Partner marketing"
  ],
  "Design & Creative": [
    "UI design","UX design","Product design","Interaction design",
    "Visual design","Graphic design","Motion design","Brand design",
    "Design systems","Component libraries","Design tokens",
    "Typography","Color theory","Grid systems","Responsive design",
    "Accessibility design (WCAG)","Inclusive design",
    "User research","Usability testing","User interviews","Card sorting",
    "Wireframing","Prototyping","Low-fidelity prototyping","High-fidelity prototyping",
    "Information architecture","Sitemap design","Navigation design",
    "Design thinking","Human-centered design","Design sprints","Jobs-to-be-done",
    "Figma","Sketch","Adobe XD","InVision","Zeplin","Abstract",
    "Adobe Photoshop","Adobe Illustrator","Adobe InDesign",
    "Adobe After Effects","Adobe Premiere Pro","Adobe Lightroom",
    "Cinema 4D","Blender","SketchUp","Procreate","Canva","Miro","FigJam",
    "Logo design","Brand identity","Brand guidelines",
    "Packaging design","Print design","Editorial design",
    "Infographic design","Icon design","Illustration",
    "Photography","Photo editing","Video production","Video editing",
    "Animation","2D animation","3D modeling","3D animation",
    "AR/VR design","Spatial design","Voice UI design","Conversational design",
    "Storyboarding","Visual storytelling","Presentation design",
    "UX writing","Microcopy","Design handoff","Design critique"
  ],
  "Finance & Accounting": [
    "Financial modeling","Valuation","DCF analysis","LBO modeling","M&A",
    "Due diligence","Financial analysis","Financial reporting",
    "Financial planning & analysis (FP&A)","Budgeting","Forecasting","Variance analysis",
    "Cost accounting","Management accounting","Financial accounting",
    "GAAP","IFRS","Revenue recognition",
    "Accounts payable","Accounts receivable","General ledger",
    "Bank reconciliation","Month-end close","Year-end close",
    "Audit preparation","Internal audit","External audit",
    "Internal controls","SOX compliance",
    "Tax planning","Corporate tax","VAT/GST","Transfer pricing",
    "Treasury management","Cash flow management","Working capital management",
    "Risk management","Credit risk","Market risk","Operational risk",
    "Hedging","Derivatives","Portfolio management","Asset management",
    "Investment analysis","Equity research","Fixed income","Alternative investments",
    "Private equity","Venture capital","Real estate finance",
    "Corporate finance","Investment banking","Capital markets",
    "IPO preparation","Debt financing","Equity financing",
    "Excel (financial modeling)","Power BI","QuickBooks","Xero","Sage",
    "SAP Finance","Oracle ERP","NetSuite","Workday Finance",
    "Bloomberg Terminal","FactSet","Capital IQ","Refinitiv",
    "Regulatory reporting","Financial compliance","AML/KYC",
    "ESG reporting","Sustainability accounting","Carbon accounting",
    "Payroll processing","Expense management","Management reporting","Investor relations"
  ],
  "Sales & Business Dev": [
    "B2B sales","B2C sales","SaaS sales","Enterprise sales","SMB sales",
    "Inside sales","Field sales","Channel sales","Partner sales",
    "Solution selling","Consultative selling","SPIN selling",
    "Challenger sale","MEDDIC","MEDDPICC","Value-based selling",
    "Sales cycle management","Pipeline management","Pipeline generation",
    "Lead generation","Prospecting","Cold calling","Cold emailing",
    "Social selling","LinkedIn prospecting","Outbound sales","Inbound sales",
    "Account management","Key account management","Strategic account management",
    "Customer success","Customer retention","Churn reduction",
    "Upselling","Cross-selling","Expansion revenue",
    "Contract negotiation","Pricing strategy","Proposal writing","RFP response",
    "CRM","Salesforce","HubSpot CRM","Pipedrive","Close.io",
    "ZoomInfo","Outreach.io","Salesloft","LinkedIn Sales Navigator","Apollo","Cognism",
    "Gong","Chorus",
    "Business development","Partnership development","Channel partnerships",
    "Alliance management","Market expansion","Territory management",
    "Quota attainment","Sales forecasting","Revenue forecasting",
    "Revenue operations (RevOps)","Sales enablement","Sales training",
    "Competitive intelligence","Win/loss analysis",
    "Demo delivery","POC management","Sales operations","Trade shows","Networking"
  ],
  "Project & Product Mgmt": [
    "Project planning","Project scheduling","Resource allocation",
    "Budget management","Risk management","Issue management",
    "Stakeholder management","Change management","Requirements gathering",
    "Scope management","Quality management","Dependency management",
    "Agile","Scrum","Kanban","SAFe","LeSS","Waterfall","PRINCE2","PMP",
    "PMO management","Portfolio management","Program management",
    "JIRA","Confluence","Asana","Trello","Monday.com","Notion",
    "Microsoft Project","Smartsheet","Basecamp","Wrike","ClickUp",
    "Miro","Lucidchart","Productboard","Aha!",
    "Sprint planning","Retrospectives","Daily standups","Backlog grooming",
    "User story writing","Acceptance criteria","Definition of done",
    "OKRs","KPIs","Goal setting","Roadmapping","Product roadmap",
    "Product discovery","Product strategy","Product vision",
    "Market analysis","Competitive analysis","Opportunity sizing",
    "Prioritization (RICE / ICE / Kano / MoSCoW)",
    "User journey mapping","Persona development",
    "A/B testing (product)","Feature flags","Product analytics",
    "Go-to-market coordination","Launch management","Release management",
    "Technical product management","Data product management",
    "Cross-functional collaboration","Executive reporting","Status reporting",
    "Client management","Vendor management","Contract management",
    "SLA management","Business analysis","Process mapping","Process improvement"
  ],
  "Operations & Supply Chain": [
    "Operations management","Process improvement","Lean management",
    "Six Sigma","Lean Six Sigma","Kaizen","Value stream mapping",
    "Continuous improvement (CI)","Root cause analysis","5 Whys",
    "Quality management","ISO 9001","TQM","Quality assurance","Quality control",
    "Supply chain management","Supply chain planning","S&OP",
    "Demand planning","Demand forecasting","Inventory management",
    "Procurement","Strategic sourcing","Vendor management","Supplier evaluation",
    "Contract management","Category management",
    "Logistics","Warehouse management","Distribution management",
    "Transportation management","Fleet management","Last-mile delivery",
    "Cold chain management","Customs and compliance","Import/export","Incoterms",
    "ERP systems","SAP","Oracle ERP","Microsoft Dynamics","NetSuite",
    "Network optimization","Cost reduction","Operational efficiency",
    "SLA management","KPI management",
    "Business continuity","Disaster recovery planning",
    "Facilities management","Health & safety","OSHA compliance",
    "Environmental compliance","Sustainability operations","ESG",
    "Manufacturing operations","Production planning","Lean manufacturing",
    "Industry 4.0","Automation","Robotic process automation (RPA)",
    "Customer operations","Order management","Returns management","Field operations"
  ],
  "HR & People": [
    "Recruitment","Talent acquisition","Executive search","Headhunting",
    "Employer branding","Job posting","Job analysis","Job grading",
    "Behavioral interviewing","Structured interviewing","Competency-based interviewing",
    "Assessment centres","Background screening",
    "Onboarding","Offboarding","New hire orientation",
    "Performance management","Performance reviews","360-degree feedback",
    "Continuous performance feedback",
    "Compensation & benefits","Salary benchmarking","Total rewards",
    "Equity compensation","Benefits administration","Payroll management",
    "HRIS","Workday","SAP SuccessFactors","BambooHR","Oracle HCM",
    "ADP","Personio","Rippling","Greenhouse","Lever","iCIMS",
    "Learning & development (L&D)","Training design","Training delivery",
    "E-learning","LMS","Instructional design",
    "Succession planning","Talent management","Talent mapping",
    "Organizational development","Change management","Culture development",
    "Employee engagement","Employee experience","Employee relations",
    "Conflict resolution","Disciplinary procedures","Grievance handling",
    "Employment law","Labor law","GDPR for HR",
    "Diversity, equity & inclusion (DEI)","DEI strategy","Pay equity analysis",
    "Organizational design","Workforce planning","Headcount planning",
    "HR analytics","People analytics","HR reporting",
    "HR policy development","Coaching","Mentoring","Leadership development",
    "Team building","HR business partnering","Strategic HR"
  ],
  "Leadership & Strategy": [
    "Strategic planning","Business strategy","Corporate strategy",
    "Competitive strategy","Growth strategy","Innovation strategy",
    "Digital transformation","Business transformation",
    "Organizational design","Operating model design",
    "Change management","Transformation leadership",
    "P&L management","Budget ownership","Cost management","Revenue growth",
    "Team leadership","People management","Line management",
    "Executive communication","Board reporting","Investor relations",
    "C-suite communication","Board presentations",
    "Decision-making","Critical thinking","Problem-solving",
    "Systems thinking","Strategic thinking","Design thinking",
    "Innovation management","Ideation","Lean startup",
    "Crisis management","Risk management (strategic)",
    "Negotiation","Influence without authority",
    "Cross-functional leadership","Matrix management",
    "Remote leadership","Distributed team leadership",
    "Culture building","Values development","Purpose-driven leadership",
    "Executive coaching","Mentoring","Succession planning",
    "OKRs","Balanced Scorecard","Strategy execution",
    "Mergers & acquisitions","Post-merger integration",
    "Private equity portfolio management","Joint ventures",
    "ESG strategy","Sustainability strategy","Corporate responsibility",
    "Facilitation","Workshop facilitation","Strategy facilitation"
  ],
  "Communication & Writing": [
    "Business writing","Technical writing","Report writing",
    "Proposal writing","Grant writing","Bid writing",
    "Copywriting","Content writing","Creative writing",
    "UX writing","Microcopy","Marketing copy","Ad copywriting",
    "Email writing","Newsletter writing","Blog writing",
    "Journalism","Feature writing","Investigative journalism",
    "Script writing","Screenwriting","Podcast scripting",
    "Social media writing","Thought leadership writing",
    "Academic writing","Research writing","White papers","Case studies",
    "Press releases","Media statements","Speech writing",
    "Editing","Proofreading","Copy editing","Substantive editing",
    "Translation","Localization","Transcription",
    "Presentation skills","Public speaking","Keynote speaking",
    "Storytelling","Narrative design","Pitching",
    "Negotiation communication","Persuasion",
    "Cross-cultural communication","Intercultural competence",
    "Active listening","Facilitation","Meeting management",
    "Internal communication","External communication",
    "Crisis communication","Media communication",
    "Scientific communication","Policy communication",
    "Documentation writing","SOP development",
    "Communication strategy","Brand voice development","Tone of voice",
    "Plain language writing","Accessibility in writing"
  ],
  "Research & Analysis": [
    "Qualitative research","Quantitative research","Mixed-methods research",
    "Market research","User research","Consumer research",
    "Academic research","Secondary research","Desk research","Literature review",
    "Systematic review","Meta-analysis",
    "Survey design","Questionnaire design","Panel research",
    "Interview design","Focus groups","Ethnographic research",
    "Observational research","Case study research","Grounded theory",
    "Statistical analysis","Content analysis","Thematic analysis",
    "Discourse analysis","Narrative analysis",
    "Competitive analysis","Industry analysis","Landscape analysis",
    "SWOT analysis","PESTLE analysis","Porter's Five Forces",
    "Business case development","Financial analysis","Policy analysis",
    "Due diligence","Risk assessment","Feasibility analysis",
    "Cost-benefit analysis","Impact assessment",
    "Economic analysis","Econometrics",
    "Research reporting","Insight generation","Synthesis",
    "Primary data collection","Data triangulation",
    "NVivo","Atlas.ti",
    "Research ethics","Grant writing","Research proposals","Academic publishing",
    "Citation management","Mendeley","Zotero"
  ],
  "Healthcare": [
    "Patient assessment","Clinical assessment","Physical examination",
    "Patient care","Patient advocacy","Bedside manner",
    "Nursing","Critical care nursing","Emergency nursing","Paediatric nursing",
    "Midwifery","Physiotherapy","Occupational therapy",
    "Speech and language therapy","Dietetics","Nutrition",
    "Pharmacy","Pharmacology","Medication management","Prescribing",
    "Radiology","Medical imaging","Ultrasound",
    "Pathology","Histology","Microbiology",
    "Surgery","Surgical assistance","Theatre nursing",
    "Anaesthesiology","Pain management",
    "Emergency medicine","Trauma care","Resuscitation",
    "Intensive care (ICU)","High dependency care",
    "Geriatrics","Paediatrics","Neonatology",
    "Psychiatry","Mental health care","Addiction medicine",
    "Psychology","Counselling","Cognitive behavioural therapy (CBT)",
    "Social work","Case management","Care coordination",
    "Electronic health records (EHR)","Epic","Cerner","Meditech",
    "Healthcare operations","Hospital management","Bed management",
    "Clinical governance","Clinical audit","Quality improvement (QI)",
    "Patient safety","Infection prevention and control (IPC)",
    "Wound care","IV therapy","Triage",
    "First aid","CPR","BLS","ALS","ACLS",
    "Mental health first aid","Safeguarding",
    "Public health","Epidemiology","Disease surveillance",
    "Healthcare policy","GDPR (healthcare)","CQC","JCAHO",
    "Health informatics","Medical coding","ICD-10","Medical billing","HIPAA compliance",
    "Clinical trials","Good Clinical Practice (GCP)","Research ethics",
    "Telehealth","Digital health","Health technology assessment"
  ],
  "Legal & Compliance": [
    "Contract law","Contract drafting","Contract negotiation",
    "Commercial law","Corporate law","Company law",
    "Employment law","Labor law","Industrial relations",
    "Intellectual property (IP)","Patents","Trademarks","Copyright",
    "Data protection","GDPR","CCPA","Privacy law",
    "Regulatory compliance","Regulatory affairs",
    "Financial compliance","Anti-money laundering (AML)",
    "Know Your Customer (KYC)","Sanctions screening",
    "MiFID II","FCA compliance","SEC compliance",
    "SOX compliance","PCI DSS","ISO 27001",
    "Risk management (legal)","Compliance management",
    "Legal research","Case law research","Legislative research",
    "Legal writing","Legal drafting","Brief writing",
    "Litigation","Civil litigation","Commercial litigation",
    "Arbitration","Mediation","Alternative dispute resolution (ADR)",
    "Negotiation (legal)","Settlement negotiations",
    "Due diligence (legal)",
    "Corporate governance","Board secretariat","Company secretarial",
    "M&A legal",
    "Real estate law","Property law","Conveyancing",
    "Tax law","Criminal law","Family law",
    "Immigration law","Planning law","Environmental law",
    "Public law","EU law","International law","Cross-border transactions",
    "Legal project management","Legal operations (LegalOps)",
    "Legal technology (LegalTech)","Contract management systems",
    "Document review","eDiscovery",
    "Policy development","Policy analysis","Regulatory strategy"
  ],
  "Education & Training": [
    "Curriculum development","Instructional design","Learning design",
    "E-learning development","Blended learning","Flipped classroom",
    "Articulate Storyline","Adobe Captivate","Rise 360",
    "Moodle","Canvas","Blackboard","Teachable","TalentLMS",
    "Training delivery","Workshop design","Workshop facilitation",
    "Coaching","Adult learning principles","Bloom's taxonomy",
    "Needs analysis","Learning outcomes","Assessment design",
    "Formative assessment","Summative assessment",
    "Gamification","Microlearning","Learning analytics",
    "Knowledge management","Academic advising","Student support",
    "SEN/SEND","Special educational needs",
    "Early years education","Primary education","Secondary education",
    "Higher education","Corporate training","Professional development",
    "Leadership development","Sales training","Technical training",
    "Compliance training","Onboarding training",
    "Mentoring","Train the trainer","Coaching (professional)",
    "Educational technology (EdTech)","Virtual classroom","Video-based learning",
    "Instructional writing","Course creation","Content development",
    "Performance consulting","Learning strategy","L&D strategy"
  ],
  "Soft Skills": [
    "Leadership","Communication","Teamwork","Collaboration",
    "Problem-solving","Critical thinking","Analytical thinking",
    "Creativity","Innovation","Adaptability","Flexibility","Resilience",
    "Time management","Prioritisation","Self-management","Accountability",
    "Attention to detail","Accuracy","Reliability","Dependability",
    "Emotional intelligence (EQ)","Empathy","Self-awareness",
    "Conflict resolution","Negotiation","Persuasion","Influence",
    "Decision-making","Judgement","Strategic thinking",
    "Presentation skills","Public speaking","Storytelling",
    "Active listening","Written communication","Verbal communication",
    "Intercultural communication","Cross-cultural collaboration",
    "Stakeholder management","Relationship building","Networking",
    "Mentoring","Coaching","Feedback delivery",
    "Project management (general)","Organisation","Planning",
    "Initiative","Proactiveness","Continuous learning","Growth mindset",
    "Customer focus","Client relationship management",
    "Ethical judgement","Integrity","Professionalism",
    "Facilitation","Meeting management","Consensus building",
    "Delegation","Resource management","Budget awareness",
    "Remote working","Virtual collaboration","Digital literacy"
  ]
};
